-- ========================================================
-- TransportX Supabase Database Schema
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard)
-- Project: https://znczyfkpcpkmhutlmenh.supabase.co
-- ========================================================

-- 1. TRIPS TABLE
CREATE TABLE IF NOT EXISTS public.trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lr_no TEXT,
  party_name TEXT NOT NULL,
  party_phone TEXT,
  vehicle_no TEXT NOT NULL,
  vehicle_type TEXT,
  from_city TEXT NOT NULL,
  to_city TEXT NOT NULL,
  date TEXT NOT NULL,
  material TEXT,
  weight TEXT,
  driver_name TEXT,
  driver_mobile TEXT,
  amount NUMERIC DEFAULT 0,
  advance NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  payment_status TEXT DEFAULT 'Pending',
  delivery_status TEXT DEFAULT 'Pending',
  diesel_expense NUMERIC DEFAULT 0,
  toll_expense NUMERIC DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PARTIES TABLE
CREATE TABLE IF NOT EXISTS public.parties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  gstin TEXT,
  city TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. ROW LEVEL SECURITY (RLS) & PUBLIC POLICIES FOR ANON / PUBLISHABLE KEY ACCESS
ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public trips policy" ON public.trips;
CREATE POLICY "Public trips policy" ON public.trips FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public parties policy" ON public.parties;
CREATE POLICY "Public parties policy" ON public.parties FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public settings policy" ON public.settings;
CREATE POLICY "Public settings policy" ON public.settings FOR ALL USING (true) WITH CHECK (true);
