import React, { useState, useRef } from 'react';
import { 
  Download, 
  Upload, 
  FileSpreadsheet, 
  CheckCircle2, 
  AlertTriangle, 
  ShieldCheck,
  Cloud,
  Database,
  Code2,
  Copy,
  Check,
  ExternalLink
} from 'lucide-react';
import { 
  exportDatabaseToJson, 
  exportTripsToCsv, 
  restoreDatabaseFromJson 
} from '../db';
import { isSupabaseEnabled } from '../utils/supabase';

const SUPABASE_SCHEMA_SQL = `-- TransportX Supabase Database Schema
CREATE TABLE IF NOT EXISTS public.trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lr_no TEXT,
  party_name TEXT NOT NULL,
  party_phone TEXT,
  vehicle_no TEXT NOT NULL,
  vehicle_type TEXT,
  from_city TEXT NOT NULL,
  to_city TEXT NOT NULL,
  date TEXT NOT NULL,
  material TEXT,
  weight TEXT,
  driver_name TEXT,
  driver_mobile TEXT,
  amount NUMERIC DEFAULT 0,
  advance NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  payment_status TEXT DEFAULT 'Pending',
  delivery_status TEXT DEFAULT 'Pending',
  diesel_expense NUMERIC DEFAULT 0,
  toll_expense NUMERIC DEFAULT 0,
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  gstin TEXT,
  city TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public trips policy" ON public.trips FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public parties policy" ON public.parties FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public settings policy" ON public.settings FOR ALL USING (true) WITH CHECK (true);`;

export default function DatabaseCenter({ trips = [], parties = [], onDatabaseRestored, dbMeta = {} }) {
  const [restoring, setRestoring] = useState(false);
  const [restoreMessage, setRestoreMessage] = useState(null);
  const [showSqlModal, setShowSqlModal] = useState(false);
  const [copiedSql, setCopiedSql] = useState(false);
  const fileInputRef = useRef(null);

  const handleCopySql = () => {
    navigator.clipboard?.writeText(SUPABASE_SCHEMA_SQL);
    setCopiedSql(true);
    setTimeout(() => setCopiedSql(false), 2500);
  };

  const handleFileUpload = async (e) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setRestoring(true);
    setRestoreMessage(null);

    const reader = new FileReader();
    reader.onload = async (event) => {
      try {
        const text = event.target?.result;
        const result = await restoreDatabaseFromJson(text);
        if (result.success) {
          setRestoreMessage({
            type: 'success',
            text: `Backup restored successfully! Loaded ${result.count} trip entries.`
          });
          if (onDatabaseRestored) onDatabaseRestored();
        } else {
          setRestoreMessage({
            type: 'error',
            text: `Restore failed: ${result.error || 'Invalid file format'}`
          });
        }
      } catch (err) {
        setRestoreMessage({
          type: 'error',
          text: `Failed to open backup: ${err.message}`
        });
      } finally {
        setRestoring(false);
        if (fileInputRef.current) fileInputRef.current.value = '';
      }
    };
    reader.readAsText(file);
  };

  return (
    <div className="space-y-4 sm:space-y-6 max-w-4xl mx-auto">
      
      {/* Header */}
      <div>
        <h2 className="text-lg sm:text-2xl font-bold text-zinc-900 dark:text-white tracking-tight">
          Backup & Data Protection
        </h2>
        <p className="text-[11px] sm:text-xs text-zinc-500 dark:text-zinc-400 mt-0.5">
          Download offline backups of your accounts or restore previously saved records
        </p>
      </div>

      {/* Database Mode Status Card */}
      <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-4 sm:p-5 shadow-xs">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-start gap-3">
            <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 border ${
              isSupabaseEnabled()
                ? 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400 border-emerald-200 dark:border-emerald-800/40'
                : 'bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 border-zinc-200 dark:border-zinc-700'
            }`}>
              {isSupabaseEnabled() ? <Cloud className="w-5 h-5" /> : <Database className="w-5 h-5" />}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-zinc-900 dark:text-white text-xs sm:text-sm">
                  {isSupabaseEnabled() ? 'Supabase Cloud Database' : 'Localhost Development Database'}
                </h3>
                <span className={`px-2 py-0.5 rounded-full text-[10px] font-semibold border ${
                  isSupabaseEnabled()
                    ? 'bg-emerald-50 dark:bg-emerald-950/50 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800'
                    : 'bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border-zinc-200 dark:border-zinc-700'
                }`}>
                  {isSupabaseEnabled() ? 'Production Cloud' : 'Local IndexedDB'}
                </span>
              </div>
              <p className="text-zinc-500 dark:text-zinc-400 mt-1 text-[11px] sm:text-xs">
                {isSupabaseEnabled()
                  ? 'Active in production on https://znczyfkpcpkmhutlmenh.supabase.co with dual-redundant local cache.'
                  : 'Operating in local offline mode on localhost. Cloud database is automatically active in production.'}
              </p>
            </div>
          </div>
          <button
            onClick={() => setShowSqlModal(true)}
            className="self-start sm:self-auto px-3 py-1.5 rounded-xl border border-zinc-200 dark:border-zinc-700 bg-zinc-50 hover:bg-zinc-100 dark:bg-zinc-800/60 dark:hover:bg-zinc-800 text-zinc-700 dark:text-zinc-200 text-xs font-semibold flex items-center gap-1.5 transition cursor-pointer shrink-0"
          >
            <Code2 className="w-3.5 h-3.5 text-zinc-500" />
            <span>Supabase SQL Setup</span>
          </button>
        </div>
      </div>

      {/* Safety Notice Card */}
      <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-4 sm:p-5 shadow-xs">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 sm:w-9 sm:h-9 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 flex items-center justify-center shrink-0 border border-emerald-200 dark:border-emerald-800/40">
            <ShieldCheck className="w-4 h-4 sm:w-5 sm:h-5" />
          </div>
          <div className="text-xs sm:text-sm">
            <h3 className="font-bold text-zinc-900 dark:text-white text-xs sm:text-sm">
              Your Data is Safely Saved on this Device
            </h3>
            <p className="text-zinc-600 dark:text-zinc-300 mt-1 leading-relaxed text-[11px] sm:text-xs">
              All truck records, freight accounts, and party ledgers are automatically saved locally on this browser. 
              Closing the window, restarting your device, or refreshing the page will <strong>never erase your data</strong>.
            </p>
            <p className="text-zinc-400 dark:text-zinc-500 mt-2 text-[10px] sm:text-[11px]">
              Tip: Click <strong>Download Backup</strong> regularly to keep an offline file on your phone or laptop.
            </p>
          </div>
        </div>
      </div>

      {/* Action Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4">
        
        {/* 1. Download Backup */}
        <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-4 sm:p-5 flex flex-col justify-between shadow-xs">
          <div>
            <div className="w-8 h-8 rounded-xl bg-zinc-100 dark:bg-zinc-800 text-zinc-800 dark:text-zinc-200 flex items-center justify-center mb-2.5">
              <Download className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-zinc-900 dark:text-white text-xs sm:text-sm">Download Backup</h3>
            <p className="text-[11px] text-zinc-400 mt-1">
              Saves a complete backup file containing all truck records, parties, and accounts.
            </p>
          </div>
          <button
            onClick={exportDatabaseToJson}
            className="mt-4 w-full py-2.5 sm:py-2 bg-zinc-900 hover:bg-zinc-800 dark:bg-white dark:hover:bg-zinc-100 text-white dark:text-zinc-900 rounded-xl text-sm sm:text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer shadow-xs active:scale-95"
          >
            <Download className="w-4 h-4" />
            <span>Download Backup File</span>
          </button>
        </div>

        {/* 2. Restore from Backup */}
        <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-4 sm:p-5 flex flex-col justify-between shadow-xs">
          <div>
            <div className="w-8 h-8 rounded-xl bg-zinc-100 dark:bg-zinc-800 text-zinc-800 dark:text-zinc-200 flex items-center justify-center mb-2.5">
              <Upload className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-zinc-900 dark:text-white text-xs sm:text-sm">Restore from Backup</h3>
            <p className="text-[11px] text-zinc-400 mt-1">
              Upload your previously saved backup file to restore records on any device.
            </p>
          </div>
          <div>
            <input
              type="file"
              ref={fileInputRef}
              onChange={handleFileUpload}
              accept=".json"
              className="hidden"
            />
            <button
              onClick={() => fileInputRef.current?.click()}
              disabled={restoring}
              className="mt-4 w-full py-2.5 sm:py-2 bg-zinc-100 hover:bg-zinc-200 dark:bg-zinc-800 dark:hover:bg-zinc-700 text-zinc-800 dark:text-zinc-200 rounded-xl text-sm sm:text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer border border-zinc-200 dark:border-zinc-700 disabled:opacity-50 active:scale-95"
            >
              <Upload className="w-4 h-4" />
              <span>{restoring ? 'Restoring...' : 'Select Backup File'}</span>
            </button>
          </div>
        </div>

        {/* 3. Export to Excel */}
        <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-4 sm:p-5 flex flex-col justify-between shadow-xs">
          <div>
            <div className="w-8 h-8 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-300 flex items-center justify-center mb-2.5 border border-emerald-200 dark:border-emerald-800/40">
              <FileSpreadsheet className="w-4 h-4" />
            </div>
            <h3 className="font-bold text-zinc-900 dark:text-white text-xs sm:text-sm">Export to Excel</h3>
            <p className="text-[11px] text-zinc-400 mt-1">
              Downloads logbook as a clean spreadsheet ready to open in Microsoft Excel or Google Sheets.
            </p>
          </div>
          <button
            onClick={exportTripsToCsv}
            className="mt-4 w-full py-2.5 sm:py-2 bg-emerald-50 hover:bg-emerald-100 dark:bg-emerald-950/40 dark:hover:bg-emerald-900/60 text-emerald-800 dark:text-emerald-300 rounded-xl text-sm sm:text-xs font-semibold flex items-center justify-center gap-1.5 transition cursor-pointer border border-emerald-200 dark:border-emerald-800/50 active:scale-95"
          >
            <FileSpreadsheet className="w-4 h-4" />
            <span>Download Excel Sheet</span>
          </button>
        </div>

      </div>

      {/* Restore Feedback Message */}
      {restoreMessage && (
        <div className={`p-3 rounded-xl border text-xs flex items-center gap-2 ${
          restoreMessage.type === 'success'
            ? 'bg-emerald-50 border-emerald-200 text-emerald-800 dark:bg-emerald-950/40 dark:border-emerald-800/50 dark:text-emerald-300'
            : 'bg-rose-50 border-rose-200 text-rose-800 dark:bg-rose-950/40 dark:border-rose-800/50 dark:text-rose-300'
        }`}>
          {restoreMessage.type === 'success' ? (
            <CheckCircle2 className="w-4 h-4 shrink-0 text-emerald-600 dark:text-emerald-400" />
          ) : (
            <AlertTriangle className="w-4 h-4 shrink-0 text-rose-600 dark:text-rose-400" />
          )}
          <span>{restoreMessage.text}</span>
        </div>
      )}

      {/* Supabase SQL Setup Modal */}
      {showSqlModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
          <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl max-w-2xl w-full p-4 sm:p-5 shadow-2xl space-y-3.5 max-h-[90vh] flex flex-col">
            <div className="flex items-center justify-between border-b border-zinc-100 dark:border-zinc-800 pb-3">
              <div className="flex items-center gap-2">
                <Cloud className="w-5 h-5 text-emerald-600" />
                <h3 className="font-bold text-zinc-900 dark:text-white text-sm sm:text-base">
                  Supabase Database Schema Setup
                </h3>
              </div>
              <button
                onClick={() => setShowSqlModal(false)}
                className="text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-200 text-sm font-semibold cursor-pointer p-1"
              >
                ✕
              </button>
            </div>
            <p className="text-xs text-zinc-500 dark:text-zinc-400">
              Run this script once in your Supabase SQL Editor (
              <a
                href="https://supabase.com/dashboard/project/znczyfkpcpkmhutlmenh/sql/new"
                target="_blank"
                rel="noreferrer"
                className="text-emerald-600 dark:text-emerald-400 underline font-medium inline-flex items-center gap-0.5"
              >
                Open SQL Editor <ExternalLink className="w-3 h-3" />
              </a>
              ) to initialize <code>trips</code>, <code>parties</code>, and <code>settings</code> tables with public read/write policies.
            </p>
            <div className="relative flex-1 min-h-0">
              <pre className="p-3 bg-zinc-950 text-zinc-200 rounded-xl text-[11px] font-mono h-64 overflow-y-auto leading-relaxed border border-zinc-800 select-all">
                {SUPABASE_SCHEMA_SQL}
              </pre>
              <button
                onClick={handleCopySql}
                className="absolute top-2.5 right-2.5 px-2.5 py-1.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 text-white text-xs font-medium flex items-center gap-1.5 transition cursor-pointer shadow-xs active:scale-95"
              >
                {copiedSql ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copiedSql ? 'Copied!' : 'Copy SQL'}</span>
              </button>
            </div>
            <div className="flex justify-between items-center pt-2 border-t border-zinc-100 dark:border-zinc-800">
              <span className="text-[11px] text-zinc-400">
                Project: <code>znczyfkpcpkmhutlmenh.supabase.co</code>
              </span>
              <button
                onClick={() => setShowSqlModal(false)}
                className="px-4 py-2 bg-zinc-900 hover:bg-zinc-800 dark:bg-white dark:hover:bg-zinc-100 text-white dark:text-zinc-900 rounded-xl text-xs font-semibold cursor-pointer"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
