import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://znczyfkpcpkmhutlmenh.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_uNLo2PVuzxyirMCKKKRSEA_m_19YrCQ';

export const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Cloud database is the sole source of truth across all devices.
 */
export const isSupabaseEnabled = () => {
  return Boolean(supabaseUrl && supabaseKey);
};

export const SUPABASE_SCHEMA_SQL = `-- Sai Transport Supabase Cloud Database Schema
CREATE TABLE IF NOT EXISTS public.trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lr_no TEXT,
  party_name TEXT NOT NULL,
  party_phone TEXT,
  vehicle_no TEXT NOT NULL,
  vehicle_type TEXT,
  from_city TEXT NOT NULL,
  to_city TEXT NOT NULL,
  date TEXT NOT NULL,
  material TEXT,
  weight TEXT,
  driver_name TEXT NOT NULL,
  driver_mobile TEXT,
  amount NUMERIC DEFAULT 0,
  advance NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  payment_status TEXT DEFAULT 'Pending',
  delivery_status TEXT DEFAULT 'Booked',
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  phone TEXT,
  gstin TEXT,
  city TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security so publishable client key has full access across all devices
ALTER TABLE public.trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.parties DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings DISABLE ROW LEVEL SECURITY;
`;

let cachedSchemaStatus = null;

/**
 * Check whether Supabase tables (e.g., trips) exist.
 * Times out in 3 seconds to avoid blocking the app.
 */
export const checkSupabaseSchema = async () => {
  if (!isSupabaseEnabled()) return false;
  if (cachedSchemaStatus === true) return true;

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3000);
    const { error } = await supabase
      .from('trips')
      .select('id')
      .limit(1)
      .abortSignal(controller.signal);
    clearTimeout(timer);

    if (error) {
      if (error.code === 'PGRST205') {
        cachedSchemaStatus = false;
        return false;
      }
      cachedSchemaStatus = false;
      return false;
    }
    cachedSchemaStatus = true;
    return true;
  } catch (_) {
    cachedSchemaStatus = false;
    return false;
  }
};

export const getCachedSchemaStatus = () => cachedSchemaStatus;
export const setCachedSchemaStatus = (status) => { cachedSchemaStatus = status; };

// Normalizer: Supabase Row -> App Trip Object
export const mapTripFromSupabase = (row) => ({
  id: row.id,
  lrNo: row.lr_no || row.lrNo || '',
  partyName: row.party_name || row.partyName || '',
  partyPhone: row.party_phone || row.partyPhone || '',
  vehicleNo: row.vehicle_no || row.vehicleNo || '',
  vehicleType: row.vehicle_type || row.vehicleType || '14 Wheeler',
  fromCity: row.from_city || row.fromCity || '',
  toCity: row.to_city || row.toCity || '',
  date: row.date || row.trip_date || '',
  material: row.material || '',
  weight: row.weight || '',
  driverName: row.driver_name || row.driverName || '',
  driverMobile: row.driver_mobile || row.driverMobile || '',
  amount: Number(row.amount) || 0,
  advance: Number(row.advance) || 0,
  balance: Number(row.balance) || 0,
  paymentStatus: row.payment_status || row.paymentStatus || 'Pending',
  deliveryStatus: row.delivery_status || row.deliveryStatus || 'Booked',
  remarks: row.remarks || '',
  createdAt: row.created_at || row.createdAt || new Date().toISOString()
});

// Converter: App Trip Object -> Supabase Row
export const mapTripToSupabase = (trip) => {
  const payload = {
    lr_no: trip.lrNo || '',
    party_name: trip.partyName || '',
    party_phone: trip.partyPhone || '',
    vehicle_no: trip.vehicleNo || '',
    vehicle_type: trip.vehicleType || '',
    from_city: trip.fromCity || '',
    to_city: trip.toCity || '',
    date: trip.date || '',
    material: trip.material || '',
    weight: trip.weight || '',
    driver_name: trip.driverName || '',
    driver_mobile: trip.driverMobile || '',
    amount: Number(trip.amount) || 0,
    advance: Number(trip.advance) || 0,
    balance: Number(trip.balance) || 0,
    payment_status: trip.paymentStatus || 'Pending',
    delivery_status: trip.deliveryStatus || 'Booked',
    remarks: trip.remarks || '',
    updated_at: new Date().toISOString()
  };
  if (trip.id && typeof trip.id === 'number') {
    payload.id = trip.id;
  }
  return payload;
};

// Normalizer: Supabase Row -> App Party Object
export const mapPartyFromSupabase = (row) => ({
  id: row.id,
  name: row.name || '',
  phone: row.phone || '',
  gstin: row.gstin || '',
  city: row.city || '',
  address: row.address || '',
  createdAt: row.created_at || row.createdAt || new Date().toISOString()
});

// Converter: App Party Object -> Supabase Row
export const mapPartyToSupabase = (party) => {
  const payload = {
    name: party.name || '',
    phone: party.phone || '',
    gstin: party.gstin || '',
    city: party.city || '',
    address: party.address || ''
  };
  if (party.id && typeof party.id === 'number') {
    payload.id = party.id;
  }
  return payload;
};
