import { createClient } from '@supabase/supabase-js';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://znczyfkpcpkmhutlmenh.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_uNLo2PVuzxyirMCKKKRSEA_m_19YrCQ';

export const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * Cloud database is the sole source of truth across all devices.
 */
export const isSupabaseEnabled = () => {
  return Boolean(supabaseUrl && supabaseKey);
};

export const SUPABASE_SCHEMA_SQL = `-- Sai Transport Supabase Cloud Database Schema
CREATE TABLE IF NOT EXISTS public.trips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lr_no TEXT,
  party_name TEXT NOT NULL,
  party_phone TEXT,
  vehicle_no TEXT NOT NULL,
  vehicle_type TEXT,
  from_city TEXT NOT NULL,
  to_city TEXT NOT NULL,
  date TEXT NOT NULL,
  material TEXT,
  weight TEXT,
  driver_name TEXT NOT NULL,
  driver_mobile TEXT,
  amount NUMERIC DEFAULT 0,
  advance NUMERIC DEFAULT 0,
  balance NUMERIC DEFAULT 0,
  payment_status TEXT DEFAULT 'Pending',
  delivery_status TEXT DEFAULT 'Booked',
  remarks TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.parties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  phone TEXT,
  gstin TEXT,
  city TEXT,
  address TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security so publishable client key has full access across all devices
ALTER TABLE IF EXISTS public.trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.parties DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.settings DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.trips TO anon, authenticated;
GRANT ALL ON TABLE public.parties TO anon, authenticated;
GRANT ALL ON TABLE public.settings TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- Fallback open policies in case RLS is re-enabled:
ALTER TABLE IF EXISTS public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public trips access" ON public.trips;
CREATE POLICY "Public trips access" ON public.trips FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public parties access" ON public.parties;
CREATE POLICY "Public parties access" ON public.parties FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public settings access" ON public.settings;
CREATE POLICY "Public settings access" ON public.settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
`;

export const SUPABASE_FIX_RLS_SQL = `-- Quick Fix for Row-Level Security (RLS) in Supabase
-- Paste and Run this in your Supabase SQL Editor:
ALTER TABLE IF EXISTS public.trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.parties DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.settings DISABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.trips TO anon, authenticated;
GRANT ALL ON TABLE public.parties TO anon, authenticated;
GRANT ALL ON TABLE public.settings TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

ALTER TABLE IF EXISTS public.trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.parties ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public trips access" ON public.trips;
CREATE POLICY "Public trips access" ON public.trips FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public parties access" ON public.parties;
CREATE POLICY "Public parties access" ON public.parties FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public settings access" ON public.settings;
CREATE POLICY "Public settings access" ON public.settings FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
`;

/**
 * Checks if an error is caused by PostgreSQL Row Level Security (RLS).
 */
export const isRlsError = (error) => {
  if (!error) return false;
  const msg = (error.message || '').toLowerCase();
  return (
    error.code === '42501' ||
    msg.includes('row-level security') ||
    msg.includes('violates row-level') ||
    msg.includes('violates rls')
  );
};

let cachedSchemaStatus = null;

/**
 * Check whether Supabase tables exist and whether RLS permits writes.
 * Times out in 3 seconds to avoid blocking the app.
 */
export const checkSupabaseSchema = async () => {
  if (!isSupabaseEnabled()) return { status: 'offline' };
  if (cachedSchemaStatus && cachedSchemaStatus.status === 'ready') return cachedSchemaStatus;

  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3000);

    // Non-destructive probe insert to test table existence and RLS write permission
    const { error } = await supabase
      .from('trips')
      .insert([{}])
      .abortSignal(controller.signal);
    clearTimeout(timer);

    if (error) {
      if (error.code === 'PGRST205') {
        cachedSchemaStatus = { status: 'needs_schema', error: error.message };
        return cachedSchemaStatus;
      }
      if (isRlsError(error)) {
        cachedSchemaStatus = { status: 'rls_blocked', error: error.message };
        return cachedSchemaStatus;
      }
      // Any other error (e.g. 23502 not-null constraint violation) means RLS allows writes!
      cachedSchemaStatus = { status: 'ready' };
      return cachedSchemaStatus;
    }

    cachedSchemaStatus = { status: 'ready' };
    return cachedSchemaStatus;
  } catch (_) {
    cachedSchemaStatus = { status: 'ready' };
    return cachedSchemaStatus;
  }
};

export const getCachedSchemaStatus = () => cachedSchemaStatus;
export const setCachedSchemaStatus = (status) => { cachedSchemaStatus = status; };

// Normalizer: Supabase Row -> App Trip Object
export const mapTripFromSupabase = (row) => ({
  id: row.id,
  lrNo: row.lr_no || row.lrNo || '',
  partyName: row.party_name || row.partyName || '',
  partyPhone: row.party_phone || row.partyPhone || '',
  vehicleNo: row.vehicle_no || row.vehicleNo || '',
  vehicleType: row.vehicle_type || row.vehicleType || '14 Wheeler',
  fromCity: row.from_city || row.fromCity || '',
  toCity: row.to_city || row.toCity || '',
  date: row.date || row.trip_date || '',
  material: row.material || '',
  weight: row.weight || '',
  driverName: row.driver_name || row.driverName || '',
  driverMobile: row.driver_mobile || row.driverMobile || '',
  amount: Number(row.amount) || 0,
  advance: Number(row.advance) || 0,
  balance: Number(row.balance) || 0,
  paymentStatus: row.payment_status || row.paymentStatus || 'Pending',
  deliveryStatus: row.delivery_status || row.deliveryStatus || 'Booked',
  remarks: row.remarks || '',
  createdAt: row.created_at || row.createdAt || new Date().toISOString()
});

// Converter: App Trip Object -> Supabase Row
export const mapTripToSupabase = (trip) => {
  const payload = {
    lr_no: trip.lrNo || '',
    party_name: trip.partyName || '',
    party_phone: trip.partyPhone || '',
    vehicle_no: trip.vehicleNo || '',
    vehicle_type: trip.vehicleType || '',
    from_city: trip.fromCity || '',
    to_city: trip.toCity || '',
    date: trip.date || '',
    material: trip.material || '',
    weight: trip.weight || '',
    driver_name: trip.driverName || '',
    driver_mobile: trip.driverMobile || '',
    amount: Number(trip.amount) || 0,
    advance: Number(trip.advance) || 0,
    balance: Number(trip.balance) || 0,
    payment_status: trip.paymentStatus || 'Pending',
    delivery_status: trip.deliveryStatus || 'Booked',
    remarks: trip.remarks || '',
    updated_at: new Date().toISOString()
  };
  if (trip.id && typeof trip.id === 'number') {
    payload.id = trip.id;
  }
  return payload;
};

// Normalizer: Supabase Row -> App Party Object
export const mapPartyFromSupabase = (row) => ({
  id: row.id,
  name: row.name || '',
  phone: row.phone || '',
  gstin: row.gstin || '',
  city: row.city || '',
  address: row.address || '',
  createdAt: row.created_at || row.createdAt || new Date().toISOString()
});

// Converter: App Party Object -> Supabase Row
export const mapPartyToSupabase = (party) => {
  const payload = {
    name: party.name || '',
    phone: party.phone || '',
    gstin: party.gstin || '',
    city: party.city || '',
    address: party.address || ''
  };
  if (party.id && typeof party.id === 'number') {
    payload.id = party.id;
  }
  return payload;
};
